---
version: "2"

run:
  concurrency: 8
  timeout: 120s
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: ""

formatters:
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/org/project)
        - blank
        - dot
        - alias
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - godox
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    # - bodyclose
    # - containedctx
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    # - errchkjson
    # - exhaustive
    # - exhaustruct
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocyclo
    # - goheader
    # - gomodguard
    # - goprintffuncname
    # - grouper
    # - importas
    # - interfacebloat
    # - ireturn
    # - lll
    # - maintidx
    # - makezero
    # - musttag
    # - nestif
    # - nlreturn
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - testpackage
    # - wrapcheck

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy

    errcheck:
      check-type-assertions: true # Default: false
      check-blank: true # Default: false
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)

    govet:
      disable: []

    nakedret:
      max-func-lines: 1

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: camel
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
          env: upperSnake
          envconfig: upperSnake

    revive:
      rules:
        - name: exported
          disabled: true

output:
  path-prefix: ""
  formats:
    text:
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
