---
name: 📦 Build Artifacts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  GO_VERSION: "1.26"

jobs:
  build:
    name: 📦 Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS:
          - linux
          - darwin
          - windows
        ARCH:
          - arm
          - arm64
          - amd64
          - 386
        exclude:
          - OS: darwin
            ARCH: 386
          - OS: darwin
            ARCH: arm
    steps:
      - name: 🔽 Checkout Repository
        uses: actions/checkout@v6

      - name: 🏗️ Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 📦 Go Build
        id: build
        run: |
          set -e -o pipefail

          export CGO_ENABLED=0
          export GOOS="${{ matrix.OS }}"
          export GOARCH="${{ matrix.ARCH }}"

          [[ ${GOOS} == windows ]] && SUFFIX=".exe" || SUFFIX=""

          export APP_NAME="$(basename $(pwd))"
          export BUILD="${APP_NAME}-${GOOS}-${GOARCH}${SUFFIX}"
          export VERSION="$(git describe --tags --dirty  --always)"
          export GIT_COMMIT="$(git rev-parse --short HEAD)"
          export BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          export PKG_PREFIX="$(sed -rn 's/^module (.*)$/\1/p' go.mod)"

          echo "building: ${BUILD}"

          go build -trimpath -o dist/${BUILD} -ldflags "-s -w \
            -X '${PKG_PREFIX}/pkg/config.version=${VERSION}' \
            -X '${PKG_PREFIX}/pkg/config.gitCommit=${GIT_COMMIT}' \
            -X '${PKG_PREFIX}/pkg/config.buildDate=${BUILD_DATE}'" \

          echo "listing build... " && ls -lah dist/
          echo "bin_name=${BUILD}" >> $GITHUB_OUTPUT

      - name: 🚚 Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.bin_name }}
          path: dist/
